---

authorizations: &AUTHORIZATIONS
  require_attribute:
    objectClass: person

## Environment
development:
  host: <%= ENV['LDAP_HOST'] %>
  port: 636
  attribute: cn
  base: ou=users,ou=corp,dc=omada,dc=me
  admin_user: <%= ENV['LDAP_ADMIN_USER'] %>
  admin_password: <%= ENV['LDAP_ADMIN_PASSWORD'] %>
  ssl: true
  <<: *AUTHORIZATIONS

test:
  host: ENV['LDAP_HOST']
  port: 636
  attribute: cn
  base: ou=users,ou=corp,dc=omada,dc=me
  admin_user: CN=linux.bind,OU=Unix,OU=Corp,DC=omada,DC=me
  admin_password: ENV['LDAP_ADMIN_PASSWORD']
  ssl: true
  <<: *AUTHORIZATIONS

staging: &apohypaton
  host: <%= Apohypaton::Kv.load_secret("ldap/host") %>
  port: <%= Apohypaton::Kv.load_secret("ldap/port") %>
  attribute: <%= Apohypaton::Kv.load_secret("ldap/attribute") %>
  base: <%= Apohypaton::Kv.load_secret("ldap/base") %>
  admin_user: <%= Apohypaton::Kv.load_secret("ldap/admin_user") %>
  admin_password: <%= Apohypaton::Kv.load_secret("ldap/admin_password") %>
  ssl: true
  <<: *AUTHORIZATIONS

production:
  <<: *apohypaton
